"""Generate C++ data item tables from the Python implementation's static data."""

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "python" / "src" / "config"
TARGET = ROOT / "cpp" / "include" / "dlt645" / "model" / "type_definitions.h"


def read_assignment(path: Path, name: str) -> tuple[dict, ...]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == name for target in node.targets
        ):
            value = ast.literal_eval(node.value)
            if not isinstance(value, tuple) or not all(isinstance(item, dict) for item in value):
                raise ValueError(f"{name} must be a tuple of dictionaries")
            return value
    raise ValueError(f"{name} was not found in {path}")


def cpp_string(value: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"Expected a string, got {value!r}")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{escaped}"'


def main() -> None:
    energy = read_assignment(SOURCE / "energy_types.py", "ENERGY_TYPES")
    demand = read_assignment(SOURCE / "demand_types.py", "DEMAND_TYPES")
    variable = read_assignment(SOURCE / "variable_types.py", "VARIABLE_TYPES")
    event = read_assignment(SOURCE / "event_record_types.py", "EVENT_RECORD_TYPES")
    parameter = read_assignment(SOURCE / "parameter_types.py", "PARAMETER_TYPES")
    lines = [
        "// Generated by cpp/tools/generate_type_definitions.py from python/src/config.",
        "// Edit the Python definitions and rerun the generator; do not edit this file by hand.",
        "#pragma once",
        "#include <cstdint>",
        "namespace dlt645::model::definitions {",
        "struct NamedType { const char* name; const char* unit; };",
        "struct DirectType { uint32_t di; const char* name; const char* unit; const char* format; };",
    ]
    for label, entries in (("energyTypes", energy), ("demandTypes", demand)):
        lines.append(f"inline constexpr NamedType {label}[] = {{")
        for entry in entries:
            lines.append(f"    {{{cpp_string(entry['Name'])}, {cpp_string(entry['Unit'])}}},")
        lines.append("};")
    for label, entries in (("variableTypes", variable), ("eventRecordTypes", event),
                           ("parameterTypes", parameter)):
        lines.append(f"inline constexpr DirectType {label}[] = {{")
        seen = set()
        for entry in entries:
            di = int(entry["Di"], 16)
            if label == "variableTypes" and di in seen:
                raise ValueError(f"Duplicate variable DI: {entry['Di']}")
            seen.add(di)
            lines.append(
                f"    {{0x{di:08X}u, {cpp_string(entry['Name'])}, "
                f"{cpp_string(entry['Unit'])}, {cpp_string(entry['DataFormat'])}}},"
            )
        lines.append("};")
    lines.extend(["} // namespace dlt645::model::definitions", ""])
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {TARGET.relative_to(ROOT)}: {len(energy)} energy, "
          f"{len(demand)} demand, {len(variable)} variable, "
          f"{len(event)} event fields, {len(parameter)} parameter fields")


if __name__ == "__main__":
    main()
